database:
  # host: "10.70.20.50"
  host: "164.132.223.56"
  port: 3307
  schema: "um_v3"
  ensure: true
  auto_migrate: true

  migrations:
    creation_defaults: true
    defaults:
      provider:
        id: 1
        name: "Liftel"
        desc: "Default provider"

server:
  http:
    mode: "prod"
    port: 3133
    timeout: "10s"

webhooks:
  verificaciones:
    url: "https://verificaciones.liftel.es/clientes/api/v1"
    token_cache_duration: "45m"
    api:
      login: "/login.php"
      checkIfUserExists: "/tecnico.php?action=checktech"
      getCompanyByICCID: "/iccid.php"
      getCompanyByCompanyId: "/nomcliente.php"

logger:
  mode: "prod"

