database:
  # host: "10.70.20.50"
  host: "164.132.223.56"
  port: 3307
  schema: "um_v3"
  ensure: true
  auto_migrate: true

  migrations:
    creation_defaults: true
    defaults:
      user:
          id: 1
          # Other field of user are in .env file
      provider:
        liftel:
          id: 1
          name: "Liftel"
          desc: "Default provider"
        verificaciones:
          id: 2
          name: "Verificaciones"
          desc: "Verificaciones provider"

server:
  http:
    mode: "prod"
    port: 8133
    timeout: "10s"

webhooks:
  verificaciones:
    url: "https://verificaciones.liftel.es/clientes/api/v1"
    token_cache_duration: "45m"
    api:
      login: "/login.php"
      checkIfUserExists: "/tecnico.php?action=checktech"
      getCompanyByICCID: "/iccid.php"
      getCompanyByCompanyId: "/nomcliente.php"

logger:
  mode: "prod"

